---
title: Main Title
subtitle: A subtitle
format:
  nicetheme-revealjs:
    output-ext: slide.html
    template-partials:
      - title-slide.html
author:
  - name: Zapp Brannigan
    orcid: 0123-4567-8901-1111
    email: zapp@gorgeous.xxx
    affiliations: Nimbus University
date: last-modified
---

## mermaid test

```{mermaid}
%%| fig-width: 18
%%{ init: { 'flowchart': { 'curve': 'natural' } } }%%
graph LR
    START[ ] -- x1 --> f[y = 3 + 0.5*x1 + 2*x]
    START2[ ] -- x2 --> f
    f -- y --> STOP[ ]

    style START fill-opacity:0, stroke-opacity:0;
    style START2 fill-opacity:0, stroke-opacity:0;
    style STOP  fill-opacity:0, stroke-opacity:0;
```


## [{{< fa people-group size=1x >}} Group exercise: Cover your ass, Level 3]{.r-fit-text}
### Construct and variable definitions

:::: {.columns}

::: {.column width='70%' .smaller}
In the lecture, you learned how a good construct definition looks like. Apply that new skill to your model!

**Task**:

- Develop proper definitions for *all* variables and concepts in your model
- If necessary, update the model structure in [draw.io](https://www.drawio.com); increase either the *minor* version (e.g., to `0.3.0`) or only the *patch* version (e.g., `0.2.1`); export a new `xml` file.
- Provide the definitions of the model's variables and constructs in a separate markdown file.

**Deliverables**:

- Create a `CHANGELOG.md` file that explains the changes in the model in more detail.
- Push both files to your group's Github repo. 
- Write a meaningful commit message that explains the changes.
:::

::: {.column width='30%'}
Test
:::

::::

## Sensors
### Perceiving the environment

[Organisms]{.hl} have a vast range of sensors for perceiving their environment. These have been adapted to selection pressures:

- Humans don't have sensors for ultraviolet light (bees do)
- We have no sensors for radioactivity, as this was no relevant selective force
- Single-celled organism have, for example ...
    - chemoreceptors for sugar
    - tactile sense (simple membranes transmitting changes in pressure)

# Main slide {background-image="neurons.jpg" background-position="top right" background-size="600px"}

## Example slide 

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimal and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimal and elegant presention
theme.

Install the theme.

```{.bash}
quarto install extension grantmcdermott/quarto-revealjs-clean
```

Use this lean template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean
```

Use the longer demo template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```
